### ISSUE TITLE
After upgrading vsts-task-lib to 2.0.0-preview all the build stopped to work

### ISSUE THREAD

**Issue by micdenny** [jessehouwing/vsts-variable-tasks#19]
After this commit https://github.com/jessehouwing/vsts-variable-tasks/commit/bf61311c44c130ea165d370d0ee9fd24dd71dc59 all my build that rely on vsts-variable-tasks throws this error:

```
2017-01-04T13:26:01.1523800Z ==============================================================================
2017-01-04T13:26:01.1523800Z Task         : Transform value 
2017-01-04T13:26:01.1523800Z Description  : Transform value and assign to variable.
2017-01-04T13:26:01.1523800Z Version      : 1.0.1301
2017-01-04T13:26:01.1523800Z Author       : Jesse Houwing
2017-01-04T13:26:01.1523800Z Help         : Version: 1.0.1301. [More Information](https://github.com/jessehouwing/vsts-variable-tasks/wiki/)
2017-01-04T13:26:01.1523800Z ==============================================================================
2017-01-04T13:26:01.3242546Z module.js:341
2017-01-04T13:26:01.3242546Z     throw err;
2017-01-04T13:26:01.3242546Z     ^
2017-01-04T13:26:01.3242546Z 
2017-01-04T13:26:01.3398766Z Error: Cannot find module 'shelljs'
2017-01-04T13:26:01.3398766Z     at Function.Module._resolveFilename (module.js:339:15)
2017-01-04T13:26:01.3398766Z     at Function.Module._load (module.js:290:25)
2017-01-04T13:26:01.3398766Z     at Module.require (module.js:367:17)
2017-01-04T13:26:01.3398766Z     at require (internal/module.js:16:19)
2017-01-04T13:26:01.3398766Z     at Object.<anonymous> (E:\agent\_work\_tasks\VariableTransformTask_9ccfb3bb-7ec0-4626-8599-164b1f95f933\1.0.1301\node_modules\vsts-task-lib\task.js:2:13)
2017-01-04T13:26:01.3398766Z     at Module._compile (module.js:413:34)
2017-01-04T13:26:01.3398766Z     at Object.Module._extensions..js (module.js:422:10)
2017-01-04T13:26:01.3398766Z     at Module.load (module.js:357:32)
2017-01-04T13:26:01.3398766Z     at Function.Module._load (module.js:314:12)
2017-01-04T13:26:01.3398766Z     at Module.require (module.js:367:17)
2017-01-04T13:26:01.4023735Z ##[error]Exit code 1 returned from process: file name 'E:\agent\externals\node\bin\node.exe', arguments '"E:\agent\_work\_tasks\VariableTransformTask_9ccfb3bb-7ec0-4626-8599-164b1f95f933\1.0.1301\vsts-variable-transform.js"'.
```

I'm using the hosted agent in cloud.

Another problem is that you probably pushed this as non-breaking version and so I can't choose to use the old version, I just have v1 from the listbox:

![image](https://cloud.githubusercontent.com/assets/1633595/21643951/5ae384e2-d28b-11e6-9d1d-0c61a3ea2f7d.png)

What about to revert the changes, and push on the v1 a `vsts-task-lib` version that works on hosted agent, then push the preview one as v2?

**Comment by micdenny** [comment]
maybe the problem is easier, sorry but I never created a build task...

I also have an on-premises build agent, and I've checked the downloaded task, and seems to be missing the folder `node_modules` that contains all the dependencies:

![image](https://cloud.githubusercontent.com/assets/1633595/21644367/74276ade-d28d-11e6-9276-d5eb629f7082.png)

Then I tried to simply copy and paste the folder from the old release, and in fact the build start to work again.

Unfortunately I cannot use this work-around, because the on-premises build agent is used for other purposes, and I need to use the hosted one.

I would really appreciate if you can make an hotfix for this 😄

**Comment by micdenny** [comment]
I think this exclusion is the evil:

https://github.com/jessehouwing/vsts-variable-tasks/commit/bf61311c44c130ea165d370d0ee9fd24dd71dc59#diff-21a200d4914eebd27069ee29298a29edR9

```json
  "exclude": [
    "node_modules"
  ]
```

**Comment by jessehouwing** [comment]
@micdenny that exclude is needed by the Typescript compiler, otherwise it'll try to transform all the .ts files in the node modules folder. I'm checking what went wrong... But it's not that.

**Comment by micdenny** [comment]
> @micdenny that exclude is needed by the Typescript compiler, otherwise it'll try to transform all the .ts files in the node modules folder. I'm checking what went wrong... But it's not that.

ok sorry, I promise I'll try to stop myself telling stuff I don't know 😄 but what is sure, is that if I copy the folder `node_modules` in the `vsts-task-lib` everything start to work, but I don't know if it's a problem related to `vsts-task-lib` or `vsts-variable-tasks` because I don't know how the dependencies work in nodejs/vsts-tasks.

**Comment by jessehouwing** [comment]
Yeah I changed my node version and it flattens the node module structure, so it's no longer enough to just package the vsts sdk, I need to package more. The current version packages too much, but I'm going to fix that later. Hotfix underway

**Comment by jessehouwing** [comment]
Try again

**Comment by micdenny** [comment]
@jessehouwing wouldn't be better to use the latest stable version of `vsts-task-lib`? correct me if I'm wrong should be `1.1.0`: https://www.npmjs.com/package/vsts-task-lib

**Comment by micdenny** [comment]
> Try again

testing right now...

**Comment by jessehouwing** [comment]
Yes and no. I'm aligning the sdk version across my tasks. I need the preview version for the vsts-developer-tools for the standardized wildcard support. Plus, it gives me @types support and a built-in typescript binding. It's much easier to use.

I got an OK from the devs and they're expecting to ship this version without further changes soon.

**Comment by micdenny** [comment]
ok, thank you for the explaination.

just waiting for the testing results...

**Comment by micdenny** [comment]
🎉 the hotfix worked!!

thank you very much for the quick resolution!!

**Comment by jessehouwing** [comment]
You're welcome. Looks like another task was hit by this as well. Fixed the MsBuild Helper Tasks as well. Thanks for logging the issue.

PS: a review is appreciated :).Sounds like you're using my extension in more than one build ;).

**Comment by micdenny** [comment]
> PS: a review is appreciated

will do 😄

**Comment by jessehouwing** [comment]
Pushed another version that strips the dev dependencies.

**Comment by micdenny** [comment]
> Pushed another version that strips the dev dependencies.

tested, and it works.
